# TODO: Configure these values for your SonarCloud project
sonar.projectKey=sandrahtlr1806
sonar.organization=sandrahtlr1806

sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
